services:
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    container_name: timescaledb_container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=solanum_db
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data

volumes:
  timescaledb_data: